API_BASE_URL = "https://www.cbr.ru/scripts/"
API_URL_FOR_DATE = API_BASE_URL + "XML_daily.asp"
API_URL_FOR_DATE_ENG = API_BASE_URL + "XML_daily_eng.asp"
API_URL_FOR_DATE_RANGE = API_BASE_URL + "XML_dynamic.asp"
API_URL_CURRENCY_CODES = API_BASE_URL + "XML_valFull.asp"
API_XML_ELEMENT_TAG_ISO_CURRENCY_CODE = "ISO_Char_Code"
API_REQUEST_CURRENCY_CODE = "VAL_NM_RQ"
API_REQUEST_SINGLE_DATE = "date_req"
API_REQUEST_DATE_RANGE_BEGIN = "date_req1"
API_REQUEST_DATE_RANGE_END = "date_req2"

__all__ = []
